import {
  doc, getDoc, setDoc, updateDoc, collection, query, where, getDocs, serverTimestamp, limit as limitCount,
} from 'firebase/firestore';
import { db } from '../config/firebaseConfig.js';

// ============================================================================
// BROWSER-ONLY. The one place this app writes/reads /careRelationships/**.
// This is the real backend for the "search a doctor, send a request, doctor
// accepts, doctor can now track this patient" flow, and it also models the
// caregiver <-> patient invite-code link in the SAME collection so both
// dashboards (patient / doctor / caregiver, all one app+build as of the
// 2026-08-23 doctorDashboard merge) can query relationships one consistent
// way instead of two different ad hoc mechanisms.
//
// SHAPE (see CARE_CONNECTION_PROMPT.md for the original spec this
// implements):
//   careRelationships/{patientId}_{memberId}
//     patientId: string
//     memberId: string            -- a doctor's uid OR a caregiver's uid
//     memberRole: 'doctor' | 'caregiver'
//     memberName: string | null   -- denormalized display name, written at
//                                    create time so a request inbox/list
//                                    never needs a second read just to show
//                                    a name
//     patientName: string | null  -- denormalized the same way, for the
//                                    same reason on the doctor's inbox side
//     status: 'pending' | 'accepted' | 'declined' | 'revoked'
//     initiatedBy: 'patient' | 'member'
//     createdAt / respondedAt: Firestore Timestamp
//
// DETERMINISTIC DOC ID (patientId_memberId, never an auto id): this is what
// lets firestore.rules check "does an accepted relationship exist between
// this doctor and this patient" with a cheap exists()/get() on an exact
// path, instead of needing a `list` query inside a security rule. It also
// means a given patient+doctor (or patient+caregiver) pair can only ever
// have ONE relationship document -- re-sending a request after a decline
// overwrites the same doc rather than creating a duplicate.
// ============================================================================

function relationshipId(patientId, memberId) {
  return `${patientId}_${memberId}`;
}

function relationshipDocRef(patientId, memberId) {
  return doc(db, 'careRelationships', relationshipId(patientId, memberId));
}

function relationshipsCollectionRef() {
  return collection(db, 'careRelationships');
}

export const FirestoreCareRelationshipService = {
  // Patient -> doctor. Guards against re-sending a request that's already
  // pending or already accepted (returns the existing relationship instead
  // of clobbering it silently). A prior DECLINED or REVOKED relationship
  // CAN be re-sent -- that overwrites the old doc with a fresh pending one,
  // which is the desired "try again" behavior.
  async sendDoctorRequest(patientId, patientName, doctorId, doctorName) {
    const ref = relationshipDocRef(patientId, doctorId);
    const existing = await getDoc(ref);
    if (existing.exists() && ['pending', 'accepted'].includes(existing.data().status)) {
      return { alreadyExists: true, relationship: existing.data() };
    }
    const relationship = {
      patientId,
      memberId: doctorId,
      memberRole: 'doctor',
      memberName: doctorName || null,
      patientName: patientName || null,
      status: 'pending',
      initiatedBy: 'patient',
      createdAt: serverTimestamp(),
      respondedAt: null,
    };
    await setDoc(ref, relationship);
    return { alreadyExists: false, relationship };
  },

  // Caregiver invite-code redemption -> written directly as 'accepted'
  // (the code itself, generated by the patient's own account, IS the
  // patient's consent -- see FirestoreCaregiverService.js/InviteCodeEngine.js).
  // Called from the CAREGIVER's own signed-in session (useCaregiverAuth.js),
  // which is why firestore.rules allows this create when
  // request.auth.uid == memberId, not patientId -- see that file's comment.
  async createCaregiverRelationship(patientId, patientName, caregiverId, caregiverName) {
    const ref = relationshipDocRef(patientId, caregiverId);
    const relationship = {
      patientId,
      memberId: caregiverId,
      memberRole: 'caregiver',
      memberName: caregiverName || null,
      patientName: patientName || null,
      status: 'accepted',
      initiatedBy: 'patient',
      createdAt: serverTimestamp(),
      respondedAt: serverTimestamp(),
    };
    await setDoc(ref, relationship);
    return relationship;
  },

  // ==========================================================================
  // 2026-08-23 ADDITION -- patient<->caregiver connection redesign (VR
  // request: "let's make it through some other way"). The invite-code flow
  // above still generates the code and still proves the caregiver has
  // something the patient shared with them, but it no longer links
  // instantly -- redeeming a code now sends a PENDING request that the
  // PATIENT must accept, the same review step a doctor request already
  // gets. This mirrors the doctor-request shape exactly (pending ->
  // accepted/declined, deterministic patientId_memberId doc) so the whole
  // app has ONE connection model instead of two different ones.
  // ==========================================================================

  // Called from the caregiver's own session, after they've entered a valid
  // invite code (or on retry from CaregiverLinkPatientScreen.jsx). Guards
  // against re-sending while a pending/accepted relationship already exists,
  // same pattern as sendDoctorRequest above.
  async sendCaregiverRequestAsCaregiver(patientId, patientName, caregiverId, caregiverName) {
    const ref = relationshipDocRef(patientId, caregiverId);
    const existing = await getDoc(ref);
    if (existing.exists() && ['pending', 'accepted'].includes(existing.data().status)) {
      return { alreadyExists: true, relationship: existing.data() };
    }
    const relationship = {
      patientId,
      memberId: caregiverId,
      memberRole: 'caregiver',
      memberName: caregiverName || null,
      patientName: patientName || null,
      status: 'pending',
      initiatedBy: 'member',
      createdAt: serverTimestamp(),
      respondedAt: null,
    };
    await setDoc(ref, relationship);
    return { alreadyExists: false, relationship };
  },

  // Patient's inbox: every pending CAREGIVER request addressed to them --
  // the counterpart to listPendingRequestsForDoctor, just filtered the
  // other way (by patientId instead of memberId, since the patient is
  // always the fixed side of a caregiver relationship).
  async listPendingCaregiverRequestsForPatient(patientId) {
    const q = query(
      relationshipsCollectionRef(),
      where('patientId', '==', patientId),
      where('memberRole', '==', 'caregiver'),
      where('status', '==', 'pending'),
    );
    const snap = await getDocs(q);
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
  },

  // Patient accepts/declines a pending caregiver request. Only the
  // relationship's own patientId may call this -- enforced again in
  // firestore.rules, not just here.
  async respondToCaregiverRequest(patientId, caregiverId, accept) {
    const ref = relationshipDocRef(patientId, caregiverId);
    await updateDoc(ref, {
      status: accept ? 'accepted' : 'declined',
      respondedAt: serverTimestamp(),
    });
  },

  // Self-heal lookup for the CAREGIVER's own client: "has my pending
  // request been accepted yet?" Used by useCaregiverAuth.js to backfill
  // linkedPatientUid/linkedPatientName onto the caregiver's own profile
  // once a patient approves -- the caregiver's client has write access to
  // its own /caregivers/{uid} doc, so it writes that field ITSELF rather
  // than needing any cross-account write.
  async getAcceptedRelationshipForCaregiver(caregiverId) {
    const q = query(
      relationshipsCollectionRef(),
      where('memberId', '==', caregiverId),
      where('memberRole', '==', 'caregiver'),
      where('status', '==', 'accepted'),
      limitCount(1),
    );
    const snap = await getDocs(q);
    if (snap.empty) return null;
    const d = snap.docs[0];
    return { id: d.id, ...d.data() };
  },

  // Same idea, but for "do I have a request out right now, and what's its
  // status" -- lets CaregiverLinkPatientScreen.jsx show a pending/declined
  // state instead of just a binary linked/not-linked gate.
  async getRelationshipForCaregiver(caregiverId) {
    const q = query(
      relationshipsCollectionRef(),
      where('memberId', '==', caregiverId),
      where('memberRole', '==', 'caregiver'),
      limitCount(1),
    );
    const snap = await getDocs(q);
    if (snap.empty) return null;
    const d = snap.docs[0];
    return { id: d.id, ...d.data() };
  },

  // Doctor's inbox: every pending request addressed to this doctor.
  async listPendingRequestsForDoctor(doctorId) {
    const q = query(
      relationshipsCollectionRef(),
      where('memberId', '==', doctorId),
      where('memberRole', '==', 'doctor'),
      where('status', '==', 'pending'),
    );
    const snap = await getDocs(q);
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
  },

  // Doctor's actual patient roster: every accepted relationship.
  async listAcceptedPatientIdsForDoctor(doctorId) {
    const q = query(
      relationshipsCollectionRef(),
      where('memberId', '==', doctorId),
      where('memberRole', '==', 'doctor'),
      where('status', '==', 'accepted'),
    );
    const snap = await getDocs(q);
    return snap.docs.map((d) => d.data().patientId);
  },

  // Every relationship (any role, any status) belonging to one patient --
  // used for the patient-facing "Your Care Team" status list.
  async listRelationshipsForPatient(patientId) {
    const q = query(relationshipsCollectionRef(), where('patientId', '==', patientId));
    const snap = await getDocs(q);
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
  },

  // Doctor accepts/declines a pending request. Only the request's own
  // memberId (the doctor) may call this -- enforced again in
  // firestore.rules, not just here.
  async respondToDoctorRequest(patientId, doctorId, accept) {
    const ref = relationshipDocRef(patientId, doctorId);
    await updateDoc(ref, {
      status: accept ? 'accepted' : 'declined',
      respondedAt: serverTimestamp(),
    });
  },

  // Patient revokes an accepted relationship (doctor or caregiver).
  async revokeRelationship(patientId, memberId) {
    const ref = relationshipDocRef(patientId, memberId);
    await updateDoc(ref, { status: 'revoked', respondedAt: serverTimestamp() });
  },
};
