import { useState, useCallback, useEffect, useRef } from 'react';
import {
  onAuthStateChanged,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  signInWithPopup,
  updateProfile,
  signOut,
} from 'firebase/auth';
import { AuthEngine } from '../engines/AuthEngine.js';
import { InviteCodeEngine } from '../engines/InviteCodeEngine.js';
import { CaregiverProfileEngine } from '../engines/CaregiverProfileEngine.js';
import { CaregiverWeeklyUnlockEngine } from '../engines/CaregiverWeeklyUnlockEngine.js';
import { MOCK_CAREGIVER } from '../data/mockCaregiver.js';
import { auth, googleProvider, facebookProvider, isFirebaseConfigured } from '../config/firebaseConfig.js';
import { FirestoreCaregiverService } from '../services/FirestoreCaregiverService.js';
import { FirestoreCareRelationshipService } from '../services/FirestoreCareRelationshipService.js';
import { FirestorePatientDirectoryService } from '../services/FirestorePatientDirectoryService.js';

const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// The caregiver counterpart to useAuth.js/useDoctorAuth.js -- same real/
// mock branching via isFirebaseConfigured, same shared-Firebase-Auth-pool
// note (a caregiver record lives at /caregivers/{uid}, separate from
// /users/{uid} and /doctors/{uid}).
//
// LINKING NOTE: unlike doctor access-approval (a placeholder gate with no
// real backend), patient-caregiver LINKING is real and enforced --
// linkedPatientUid starts null for every fresh signup and only becomes
// non-null when a real, currently-valid invite code (generated by the
// patient's own account, see useAuth.js's generateCaregiverInviteCode) is
// resolved through FirestoreCaregiverService. Signup succeeds even if no
// code (or an invalid one) was given at signup time -- linkToPatient() can
// be retried any time after, from the dedicated "not linked yet" screen
// App.jsx shows whenever linkedPatientUid is still null.
export function useCaregiverAuth() {
  const [view, setView] = useState('login'); // 'login' | 'signup'
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [currentCaregiver, setCurrentCaregiver] = useState(null);
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isCheckingSession, setIsCheckingSession] = useState(isFirebaseConfigured);
  // 2026-08-21: same consent-plumbing pattern as useAuth.js -- see that
  // file's comment on the equivalent ref.
  const pendingConsentRef = useRef(null);

  useEffect(() => {
    if (!isFirebaseConfigured) {
      setIsCheckingSession(false);
      return undefined;
    }
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (!firebaseUser) {
        setCurrentCaregiver(null);
        setIsAuthenticated(false);
        setIsCheckingSession(false);
        return;
      }
      try {
        let profile = await FirestoreCaregiverService.getCaregiverProfile(firebaseUser.uid);
        if (!profile) {
          const consentGiven = pendingConsentRef.current === true;
          pendingConsentRef.current = null;
          profile = CaregiverProfileEngine.buildNewProfileDoc({
            name: firebaseUser.displayName || 'there',
            email: firebaseUser.email,
            authProvider: firebaseUser.providerData?.[0]?.providerId || 'password',
            privacyConsentAcceptedAt: consentGiven ? new Date().toISOString() : null,
          });
          await FirestoreCaregiverService.createCaregiverProfile(firebaseUser.uid, profile);
        }
        // 2026-08-23 SELF-HEAL: if this caregiver has a request out
        // (pendingPatientUid set, or an older account from before this
        // field existed) check whether the patient has since accepted or
        // declined it, and backfill this account's OWN doc accordingly --
        // see FirestoreCareRelationshipService.getAcceptedRelationshipForCaregiver's
        // header comment for why this is a self-write, not a cross-account one.
        if (!profile.linkedPatientUid) {
          try {
            const rel = await FirestoreCareRelationshipService.getRelationshipForCaregiver(firebaseUser.uid);
            if (rel?.status === 'accepted') {
              profile = CaregiverProfileEngine.applyPatientLink(profile, rel.patientId, rel.patientName);
              await FirestoreCaregiverService.updateCaregiverProfile(firebaseUser.uid, {
                linkedPatientUid: profile.linkedPatientUid,
                linkedPatientName: profile.linkedPatientName,
                pendingPatientUid: null,
                pendingPatientName: null,
                linkRequestStatus: 'none',
              });
            } else if (rel?.status === 'declined' && profile.linkRequestStatus !== 'declined') {
              profile = CaregiverProfileEngine.applyLinkDeclined(profile);
              await FirestoreCaregiverService.updateCaregiverProfile(firebaseUser.uid, {
                pendingPatientUid: null,
                pendingPatientName: null,
                linkRequestStatus: 'declined',
              });
            } else if (rel?.status === 'pending' && profile.linkRequestStatus !== 'pending') {
              profile = CaregiverProfileEngine.applyPendingPatientLink(profile, rel.patientId, rel.patientName);
            }
          } catch (healErr) {
            console.error('Could not check caregiver link status (non-fatal):', healErr);
          }
        }
        setCurrentCaregiver({ ...profile, uid: firebaseUser.uid });
        setIsAuthenticated(true);
      } finally {
        setIsCheckingSession(false);
      }
    });
    return unsubscribe;
  }, []);

  const login = useCallback(async ({ email, password }) => {
    const result = AuthEngine.validateLogin({ email, password });
    setErrors(result.errors);
    if (!result.valid) return false;

    if (!isFirebaseConfigured) {
      setIsSubmitting(true);
      await wait(500);
      setCurrentCaregiver(MOCK_CAREGIVER);
      setIsAuthenticated(true);
      setIsSubmitting(false);
      return true;
    }

    setIsSubmitting(true);
    try {
      await signInWithEmailAndPassword(auth, email, password);
      return true;
    } catch (err) {
      setErrors(AuthEngine.mapFirebaseError(err.code));
      return false;
    } finally {
      setIsSubmitting(false);
    }
  }, []);

  // `inviteCode` is optional at signup time -- if given and it resolves,
  // the account is linked immediately; if omitted or invalid, signup still
  // succeeds and linkToPatient() can be retried afterward.
  const signup = useCallback(async ({ name, email, password, confirmPassword, inviteCode, consentGiven = false }) => {
    const result = AuthEngine.validateSignup({ name, email, password, confirmPassword });
    if (inviteCode && !InviteCodeEngine.isValidFormat(inviteCode)) {
      result.errors.inviteCode = 'That code doesn\'t look right -- double check it with the patient.';
      result.valid = false;
    }
    setErrors(result.errors);
    if (!result.valid) return false;

    if (!isFirebaseConfigured) {
      setIsSubmitting(true);
      await wait(500);
      setCurrentCaregiver({
        ...MOCK_CAREGIVER,
        name,
        email,
        onboardingComplete: false,
        linkedPatientUid: inviteCode ? MOCK_CAREGIVER.linkedPatientUid : null,
      });
      setIsAuthenticated(true);
      setIsSubmitting(false);
      return true;
    }

    setIsSubmitting(true);
    try {
      const credential = await createUserWithEmailAndPassword(auth, email, password);
      await updateProfile(credential.user, { displayName: name });
      let profile = CaregiverProfileEngine.buildNewProfileDoc({
        name,
        email,
        authProvider: 'password',
        privacyConsentAcceptedAt: consentGiven ? new Date().toISOString() : null,
      });

      // 2026-08-23 REDESIGN: a valid code no longer links instantly -- it
      // sends the patient a request (mirrors the doctor-request flow, see
      // FirestoreCareRelationshipService.sendCaregiverRequestAsCaregiver).
      // Best-effort: a failure sending the request must never block the
      // signup that already succeeded above -- the caregiver can always
      // retry from CaregiverLinkPatientScreen.jsx afterward.
      if (inviteCode) {
        const resolved = await FirestoreCaregiverService.resolveInviteCode(InviteCodeEngine.normalize(inviteCode));
        if (resolved) {
          try {
            await FirestoreCareRelationshipService.sendCaregiverRequestAsCaregiver(
              resolved.patientUid, resolved.patientName, credential.user.uid, name,
            );
            profile = CaregiverProfileEngine.applyPendingPatientLink(profile, resolved.patientUid, resolved.patientName);
          } catch (relErr) {
            console.error('Could not send caregiver request (non-fatal):', relErr);
          }
        } else {
          setErrors({ inviteCode: "That code wasn't found -- your account was still created; ask the patient for a fresh code and try linking again from your home screen." });
        }
      }

      await FirestoreCaregiverService.createCaregiverProfile(credential.user.uid, profile);
      setCurrentCaregiver({ ...profile, uid: credential.user.uid });
      setIsAuthenticated(true);
      return true;
    } catch (err) {
      setErrors(AuthEngine.mapFirebaseError(err.code));
      return false;
    } finally {
      setIsSubmitting(false);
    }
  }, []);

  const loginWithProvider = useCallback(async (provider, consentGiven = false) => {
    if (!isFirebaseConfigured) return false;
    setErrors({});
    setIsSubmitting(true);
    pendingConsentRef.current = consentGiven;
    try {
      const authProvider = provider === 'facebook' ? facebookProvider : googleProvider;
      await signInWithPopup(auth, authProvider);
      return true;
    } catch (err) {
      pendingConsentRef.current = null;
      setErrors(AuthEngine.mapFirebaseError(err.code));
      return false;
    } finally {
      setIsSubmitting(false);
    }
  }, []);

  const logout = useCallback(async () => {
    if (isFirebaseConfigured) {
      await signOut(auth);
    }
    setIsAuthenticated(false);
    setCurrentCaregiver(null);
    setView('login');
    setErrors({});
  }, []);

  // Retry path for a caregiver who signed up without a code, or whose code
  // didn't resolve -- shown from a dedicated screen whenever
  // currentCaregiver.linkedPatientUid is still null.
  const linkToPatient = useCallback(async (rawCode) => {
    if (!InviteCodeEngine.isValidFormat(rawCode)) {
      setErrors({ inviteCode: 'That code doesn\'t look right -- double check it with the patient.' });
      return false;
    }
    setIsSubmitting(true);
    setErrors({});
    try {
      const code = InviteCodeEngine.normalize(rawCode);
      if (!isFirebaseConfigured) {
        await wait(400);
        setCurrentCaregiver((prev) => (prev ? CaregiverProfileEngine.applyPatientLink(prev, 'MOCK-PATIENT-UID', 'Robert Hayes') : prev));
        return true;
      }
      const resolved = await FirestoreCaregiverService.resolveInviteCode(code);
      if (!resolved) {
        setErrors({ inviteCode: "That code wasn't found -- ask the patient to check it, or generate a fresh one." });
        return false;
      }
      // 2026-08-23 REDESIGN: sends a pending request instead of linking
      // instantly -- see the signup() comment above for the same change.
      let requestFailed = false;
      try {
        await FirestoreCareRelationshipService.sendCaregiverRequestAsCaregiver(
          resolved.patientUid, resolved.patientName, currentCaregiver?.uid, currentCaregiver?.name,
        );
      } catch (relErr) {
        requestFailed = true;
        console.error('Could not send caregiver request:', relErr);
        setErrors({ inviteCode: 'Could not send the request right now. Please try again.' });
      }
      if (requestFailed) return false;
      setCurrentCaregiver((prev) => {
        if (!prev) return prev;
        const updated = CaregiverProfileEngine.applyPendingPatientLink(prev, resolved.patientUid, resolved.patientName);
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
          pendingPatientUid: updated.pendingPatientUid,
          pendingPatientName: updated.pendingPatientName,
          linkRequestStatus: updated.linkRequestStatus,
        });
        return updated;
      });
      return true;
    } finally {
      setIsSubmitting(false);
    }
  }, [currentCaregiver]);

  // 2026-08-27 ADDITION (VR: "antha caregiver patient username potu request
  // kudukanum" -- a caregiver-initiated alternative to the invite-code
  // flow above). Same shape as linkToPatient end-to-end (resolve an
  // identifier to a patient uid/name, send the SAME pending
  // sendCaregiverRequestAsCaregiver request, same applyPendingPatientLink
  // local-state update) -- only the resolution step differs: a username
  // lookup via FirestorePatientDirectoryService instead of an invite-code
  // redemption. Deliberately reuses the exact same request/accept
  // relationship record, so CaregiverLinkPatientScreen's existing
  // pending/declined polling (onRefreshStatus) works unchanged for
  // requests sent this way too.
  const linkToPatientByUsername = useCallback(async (rawUsername) => {
    const username = (rawUsername || '').trim();
    if (!username) {
      setErrors({ username: "Enter the patient's username." });
      return false;
    }
    setIsSubmitting(true);
    setErrors({});
    try {
      if (!isFirebaseConfigured) {
        await wait(400);
        setCurrentCaregiver((prev) => (prev ? CaregiverProfileEngine.applyPatientLink(prev, 'MOCK-PATIENT-UID', 'Robert Hayes') : prev));
        return true;
      }
      const matches = await FirestorePatientDirectoryService.searchPatients(username);
      if (!matches.length) {
        setErrors({ username: `No patient found for '${username}'. Double check the spelling with them.` });
        return false;
      }
      // 2026-08-27: a connection REQUEST is a real action (the patient
      // will see it and has to decide whether to accept a stranger), so
      // this only ever auto-sends on an EXACT username match. A fuzzy/typo
      // result (no exact hit -- see FirestorePatientDirectoryService.
      // searchPatients) is surfaced back as a suggestion instead of being
      // silently treated as "close enough" and requested automatically --
      // auto-connecting to a guessed patient on a typo would be sending a
      // real request to the wrong person, not a harmless search miss.
      if (matches[0].fuzzy) {
        setErrors({
          username: matches.length === 1
            ? `No exact match for '${username}'. Did you mean '${matches[0].username}' (${matches[0].name})? Type that exact username to send the request.`
            : `No exact match for '${username}'. Similar usernames: ${matches.map((m) => `'${m.username}'`).join(', ')} -- type the exact one to send the request.`,
        });
        return false;
      }
      const resolved = matches[0];
      let requestFailed = false;
      try {
        await FirestoreCareRelationshipService.sendCaregiverRequestAsCaregiver(
          resolved.uid, resolved.name, currentCaregiver?.uid, currentCaregiver?.name,
        );
      } catch (relErr) {
        requestFailed = true;
        console.error('Could not send caregiver request:', relErr);
        setErrors({ username: 'Could not send the request right now. Please try again.' });
      }
      if (requestFailed) return false;
      setCurrentCaregiver((prev) => {
        if (!prev) return prev;
        const updated = CaregiverProfileEngine.applyPendingPatientLink(prev, resolved.uid, resolved.name);
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
          pendingPatientUid: updated.pendingPatientUid,
          pendingPatientName: updated.pendingPatientName,
          linkRequestStatus: updated.linkRequestStatus,
        });
        return updated;
      });
      return true;
    } finally {
      setIsSubmitting(false);
    }
  }, [currentCaregiver]);

  // 2026-08-23 ADDITION: onAuthStateChanged's self-heal check only runs
  // once, at sign-in -- a caregiver sitting on CaregiverLinkPatientScreen.jsx
  // waiting for the patient to respond would otherwise never find out
  // without signing out and back in. This lets that screen poll for a
  // status change (accepted/declined) without a full page reload.
  const refreshLinkStatus = useCallback(async () => {
    if (!isFirebaseConfigured || !currentCaregiver?.uid || currentCaregiver.linkedPatientUid) return;
    try {
      const rel = await FirestoreCareRelationshipService.getRelationshipForCaregiver(currentCaregiver.uid);
      if (!rel) return;
      if (rel.status === 'accepted') {
        setCurrentCaregiver((prev) => {
          if (!prev || prev.linkedPatientUid) return prev;
          const updated = CaregiverProfileEngine.applyPatientLink(prev, rel.patientId, rel.patientName);
          FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
            linkedPatientUid: updated.linkedPatientUid,
            linkedPatientName: updated.linkedPatientName,
            pendingPatientUid: null,
            pendingPatientName: null,
            linkRequestStatus: 'none',
          });
          return updated;
        });
      } else if (rel.status === 'declined') {
        setCurrentCaregiver((prev) => {
          if (!prev || prev.linkRequestStatus === 'declined') return prev;
          const updated = CaregiverProfileEngine.applyLinkDeclined(prev);
          FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
            pendingPatientUid: null,
            pendingPatientName: null,
            linkRequestStatus: 'declined',
          });
          return updated;
        });
      }
    } catch (err) {
      console.error('Could not refresh caregiver link status (non-fatal):', err);
    }
  }, [currentCaregiver]);

  const completeOnboarding = useCallback((profile) => {
    setCurrentCaregiver((prev) => {
      if (!prev) return prev;
      const updated = CaregiverProfileEngine.applyOnboardingProfile(prev, profile);
      if (isFirebaseConfigured && prev.uid) {
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, { ...profile, onboardingComplete: true });
      }
      return updated;
    });
  }, []);

  // 2026-08-24 REDESIGN: replaces recordCheckInAnswer -- the daily/weekly
  // split now needs two distinct write paths (see CaregiverProfileEngine.js's
  // applyMicroCheckinAnswer/applyDeepCheckinAnswer). Both follow the exact
  // same "update local state, best-effort persist the relevant slice"
  // pattern the old single function used.
  const recordMicroCheckinAnswer = useCallback((questionId, value, now = new Date()) => {
    setCurrentCaregiver((prev) => {
      if (!prev) return prev;
      const updated = CaregiverProfileEngine.applyMicroCheckinAnswer(prev, questionId, value, now);
      if (isFirebaseConfigured && prev.uid) {
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
          microToday: updated.microToday,
          microDailyHistory: updated.microDailyHistory,
        });
      }
      return updated;
    });
  }, []);

  const recordDeepCheckinAnswer = useCallback((questionId, value, now = new Date()) => {
    setCurrentCaregiver((prev) => {
      if (!prev) return prev;
      const updated = CaregiverProfileEngine.applyDeepCheckinAnswer(prev, questionId, value, now);
      if (isFirebaseConfigured && prev.uid) {
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
          deepCheckin: updated.deepCheckin,
          deepCheckinHistory: updated.deepCheckinHistory,
        });
      }
      return updated;
    });
  }, []);

  // 2026-08-24 ADDITION -- the actual unlock check (VR: "once after the
  // patient completes the detection assessment, the caregiver need to be
  // there"). Reads the linked patient's latest completed assessment date,
  // hands it to CaregiverWeeklyUnlockEngine's pure decision, and if a fresh
  // set is due, generates + persists it via CaregiverProfileEngine.
  // unlockDeepCheckin. Safe to call often (App.jsx calls it on load/link and
  // CaregiverHomeSection polls it) -- it's a no-op read+compare when nothing
  // is due, same "cheap to over-call" shape as refreshLinkStatus above.
  const checkForDeepCheckinUnlock = useCallback(async () => {
    if (!isFirebaseConfigured || !currentCaregiver?.uid || !currentCaregiver?.linkedPatientUid) return;
    try {
      const latestAssessmentDate = await FirestoreCaregiverService.getLatestAssessmentDateForPatient(
        currentCaregiver.linkedPatientUid,
      );
      if (!CaregiverWeeklyUnlockEngine.shouldUnlock(latestAssessmentDate, currentCaregiver.deepCheckin)) return;
      setCurrentCaregiver((prev) => {
        if (!prev) return prev;
        // Re-check inside the updater against the freshest state -- avoids
        // a duplicate unlock if this fires twice in quick succession (e.g.
        // App.jsx's effect and a poll landing close together).
        if (!CaregiverWeeklyUnlockEngine.shouldUnlock(latestAssessmentDate, prev.deepCheckin)) return prev;
        const cycleIndex = prev.deepCheckinHistory?.length || 0;
        const updated = CaregiverProfileEngine.unlockDeepCheckin(prev, latestAssessmentDate, cycleIndex, new Date());
        FirestoreCaregiverService.updateCaregiverProfile(prev.uid, {
          deepCheckin: updated.deepCheckin,
          deepCheckinHistory: updated.deepCheckinHistory,
        });
        return updated;
      });
    } catch (err) {
      // Expected (not an error worth surfacing to the caregiver) until the
      // isAcceptedCaregiverFor firestore.rules read grant is actually
      // deployed, or if the patient hasn't completed an assessment yet --
      // logged only, same non-fatal convention as refreshLinkStatus above.
      console.error('Could not check for a new weekly check-in unlock (non-fatal):', err);
    }
  }, [currentCaregiver]);

  return {
    view,
    setView,
    isAuthenticated,
    currentCaregiver,
    errors,
    isSubmitting,
    isCheckingSession,
    login,
    signup,
    loginWithProvider,
    logout,
    linkToPatient,
    linkToPatientByUsername,
    refreshLinkStatus,
    completeOnboarding,
    recordMicroCheckinAnswer,
    recordDeepCheckinAnswer,
    checkForDeepCheckinUnlock,
  };
}
